[workspace]

members = ["crates/mc-oxide", "crates/cxx-bindings", "crates/cli"]

resolver = "2"

[workspace.dependencies]
anyhow = "1"
log = "0.4"
tokio = { version = "1", features = ["full"] }
lazy_static = "1"
